spring.application.name=AlertWIP
# Dynamiczna pula
app.executor.core-size=5
app.executor.max-size=50
app.executor.queue-capacity=100
server.port=10000

# Sciezka do skryptów
app.scripts.path=scripts/

# Dane polaczenia
spring.datasource.url=jdbc:mysql://localhost:3306/alertdb
spring.datasource.username=root
spring.datasource.password=

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Wylacza kompresje
server.compression.enabled=false
spring.mvc.async.request-timeout=-1

#Wazuh
wazuh.api.url=https://127.0.0.1:55000
wazuh.api.user=wazuh
wazuh.api.password=wazuh

wazuh.api.ignore-ssl=true