services:
  mysql-server:
    image: mysql:8.0
    container_name: alertwip-main-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=alertdb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql_main_data:/var/lib/mysql

volumes:
  mysql_main_data:
