// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ...

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNUf-9QpNNxWo5JrzKs6tvm2SUcRGO9jo',
    appId: '1:862892237479:web:81ba67733cafa1f9297182',
    messagingSenderId: '862892237479',
    projectId: 'alertapp-e2d2c',
    authDomain: 'alertapp-e2d2c.firebaseapp.com',
    storageBucket: 'alertapp-e2d2c.firebasestorage.app',
    measurementId: 'G-YVZBKEL2DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6xLBcJDaNY7fJ-9xRvrYf0Y1_D9Nn3Kg',
    appId: '1:862892237479:android:b1b6ba7441d3555b297182',
    messagingSenderId: '862892237479',
    projectId: 'alertapp-e2d2c',
    storageBucket: 'alertapp-e2d2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASLsADbASSkgxUypkmvvbWZ_86MgqR6-A',
    appId: '1:862892237479:ios:7ad707e6503d6d18297182',
    messagingSenderId: '862892237479',
    projectId: 'alertapp-e2d2c',
    storageBucket: 'alertapp-e2d2c.firebasestorage.app',
    iosBundleId: 'com.example.alertApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASLsADbASSkgxUypkmvvbWZ_86MgqR6-A',
    appId: '1:862892237479:ios:7ad707e6503d6d18297182',
    messagingSenderId: '862892237479',
    projectId: 'alertapp-e2d2c',
    storageBucket: 'alertapp-e2d2c.firebasestorage.app',
    iosBundleId: 'com.example.alertApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNUf-9QpNNxWo5JrzKs6tvm2SUcRGO9jo',
    appId: '1:862892237479:web:53e7b5ecd800d36c297182',
    messagingSenderId: '862892237479',
    projectId: 'alertapp-e2d2c',
    authDomain: 'alertapp-e2d2c.firebaseapp.com',
    storageBucket: 'alertapp-e2d2c.firebasestorage.app',
    measurementId: 'G-PRYXGX2RY5',
  );
}
