export const inputText = 'text-sm!  xl:text-xl! 2xl:text-2xl!';
export const nameLabel = 'text-sm lg:text-md xl:text-xl 2xl:text-2xl'
export const dataTable = "w-99/100 text-xs md:text-sm lg:text-md xl:text-lg 2xl:text:xl  mx-auto  table-fixed"
export const tableCaption = "bg-secondary border-b border-t text-foreground sticky z-9 bottom-0 py-2 text-md lg:text-lg xl:text-xl 2xl:text:3xl"
export const tableHeaders = "bg-secondary hover:bg-secondary gap-0 space-0 "
export const tableDiv = " mt-[2vh] mx-[1%] w-98/100 relative overflow-auto max-h-[77vh]   "
export const topDiv = "relative max-h-[10vh] items-center align-middle"
export const topH1 = "text-center my-[2vh] text-xl xl:text-2xl 2xl:text-4xl border-b pb-[2vh]"
export const topButtonGroup = "absolute left-4 top-0 flex max-w-2/5 "
export const unwrappedItemClass = "bg-selected [&_td]:align-top  sticky h-26! [&_td]:pt-4! top-11 bottom-11 hover:bg-card z-9 cursor-auto"
